require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# ===== Layout =====

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# ===== Metrics =====

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

# ===== Style =====

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

# ===== Rails =====

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*'

Rails/Exit:
  Exclude:
    - 'spec/**/*'

# ===== RSpec =====

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

